# Generated by Django 5.1.5 on 2025-02-02 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Fake', 'Fake Content'), ('Irrelevant', 'Irrelevant Post'), ('Violence', 'Sensitive Violence'), ('Nudity', 'Nudity or Sexual Content'), ('Other', 'Other Issues')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('admin_feedback', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pet.pet')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reporter', 'post')},
            },
        ),
    ]
